apimServiceName: apim-apiops-ussc-prod
namedValues:
  - name: 648b8901217d2011d4a337f7
    properties:
      displayName: app-insights-instrumentation-key
      value: 40688af1-5cb4-471c-b465-d9b4307b18fd
  - name: dev1-api-function-app-key
    properties:
      displayName: dev1-api-function-app-key
      keyVault:
        identityClientId: ba0c378d-f7b2-44e5-9e75-46a527e4b7ff
        secretIdentifier: "https://kv-pzc3njusxmg5i-prod.vault.azure.net/secrets/function-app-key/478ee1457eea4b3f9a8b1dc88bf8d630"
loggers:
  - name: appi-b5trmbkdcmrsg-dev
    properties:
      loggerType: applicationInsights
      description: App Insights
      resourceId: "/subscriptions/cfa014c2-6565-444f-8241-b3edd39a2a44/resourceGroups/rg-apiops-func-prod/providers/microsoft.insights/components/appi-pzc3njusxmg5i-prod"
      credentials:
        instrumentationKey: "{{app-insights-instrumentation-key}}"
      isBuffered: true
diagnostics:
  - name: applicationinsights
    properties:
      verbosity: Error
      loggerId: "/subscriptions/cfa014c2-6565-444f-8241-b3edd39a2a44/resourceGroups/rg-apiops-apim-prod/providers/Microsoft.ApiManagement/service/apim-apiops-ussc-prod/loggers/appi-b5trmbkdcmrsg-dev"
backends:
  - name: dev1-api-backend
    properties:
      url: "https://func-pzc3njusxmg5i-prod.azurewebsites.net/api"
      resourceid: "https://management.azure.com/subscriptions/cfa014c2-6565-444f-8241-b3edd39a2a44/resourceGroups/rg-apiops-func-prod/providers/Microsoft.Web/sites/func-pzc3njusxmg5i-prod"
apis:
  - name: dev1-api
    diagnostics:
      - name: applicationinsights
        properties:
          verbosity: Error
          loggerId: "/subscriptions/cfa014c2-6565-444f-8241-b3edd39a2a44/resourceGroups/rg-apiops-func-prod/providers/microsoft.insights/components/appi-pzc3njusxmg5i-prod"
